update few docs also update libs
GlobedGD/globed2 pull request #262
Opened 2024-12-18 15:38 UTC by larziwau

finally doneeeeee

2024-12-19 08:28 UTC, dankmeme01 requested changes

2024-12-19 10:02 UTC, larziwau commented on server/readme.md
> +    "admin": false
i thought its understable by var names

2024-12-19 10:05 UTC, larziwau commented on server/readme.md
> +| `gd_api_url`                       | `(...)`       | Base URL for GD API used for account verification |
do u mean like setting its default to "https://www.boomlings.com/database/" or something like that?

2024-12-23 13:35 UTC, larziwau commented
dont mind him lol im just testing

2025-03-09 10:03 UTC, closed without merging